### ISSUE TITLE
Add e-learning training course and O'Reilly book

### ISSUE THREAD

**Issue by hsmara** [varnish/varnish-wiki#5]
We need to add a link to the e-learning course: https://training.varnish-software.com/ to this page and sub-pages
https://www.varnish-software.com/wiki/start/index.html

We need to add a link to the O'Reilly book (https://info.varnish-software.com/getting-started-with-varnish-cache-oreilly-book) to the Varnish Web Developer FAQ here: https://www.varnish-software.com/wiki/faq/index.html

**Comment by huayra** [comment]
Added training and book links to said pages.
